export const API_REST_DOG_SET_RANDOM_IMAGE = 'API_REST_DOG_SET_RANDOM_IMAGE'
export const API_REST_DOG_SET_SEARCH_BREED = 'API_REST_DOG_SET_SEARCH_BREED'
export const API_REST_CAT_SET_RANDOM_IMAGE = 'API_REST_CAT_SET_RANDOM_IMAGE'
export const API_REST_CAT_SET_SEARCH_BREED = 'API_REST_CAT_SET_SEARCH_BREED'
